# the language
lang: en
# author info
author:
  name: bullgit
  email: haroen@bullg.it
  twitter: '@bullgit'
# title and description
title: sseeaarrcchh
description: search for search on sseeaarrcchh
# the url this will be published at
url: https://bullg.it
baseurl: /sseeaarrcchh/
# the theme colour
color: '#FFFFFF'
# location of some files
css: ['src/style.css']
scripts: ['https://cdn.rawgit.com/bullgit/badge/master/badge.js']
favicon: ../media/pixels/favicon.png
#configuration
sass:
  style: compressed
